### ISSUE TITLE
Certain Dockerfile volumes preventing pod start

### ISSUE THREAD

**Issue by awprice** [kata-containers/runtime#1591] opened 2019-04-26 01:20 UTC
We've found certain volume paths defined in the Dockerfile prevent the Pod from starting with Kata. One such example is `/sys/fs/cgroup`.

The following Dockerfile can be used to replicate:
```Dockerfile
FROM ubuntu

VOLUME /sys/fs/cgroup
```

We receive the following errors:
```
Error: failed to create containerd task: Could not run process: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/containerd/io.containerd.grpc.v1.cri/containers/sleep/volumes/a45869c2ff90df3649c035b429e23e8b935804e90cd5cfd997778ff0d64d693c\\\" to rootfs \\\"/run/kata-containers/shared/containers/sleep\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /var/lib/containerd/io.containerd.grpc.v1.cri/containers/sleep/volumes/a45869c2ff90df3649c035b429e23e8b935804e90cd5cfd997778ff0d64d693c: no such file or directory\\\"\"": unknown
```

Unfortunately we do not have control over the contents of the Dockerfiles/images and need an elegant solution for handling this in Kata.

The following paths have been found to prevent the pods from starting:
 - `/sys/fs/cgroup`

(I will add more as I find them)

I think this issue is similar to https://github.com/kata-containers/runtime/issues/1561 as both are related to the volumes defined in Docker images/OCI image specs.

**Comment by egernst** [comment] 2019-04-26 04:24
@amshinde @bergwolf can you take a look?

**Comment by grahamwhaley** [comment] 2019-04-26 08:52
Thanks @awprice - OOI, do we know what that VOLUME over-ride is trying to achieve? It feels very strange... (I know, you didn't write it, but wondered if you had some insight?)

**Comment by devimc** [comment] 2019-04-26 12:24
@awprice this issue was fixed in kata 1.6.2

**Comment by awprice** [comment] 2019-04-26 23:33
@grahamwhaley Yep it is very strange and we've run into a number of headaches with it :( 

I found this comment by a Docker maintainer from a while back that was really helpful for my understanding of what they are used for:

> Theres more reasons for having a volume than just keeping the data around; an "unnamed" volume for example, can be for performance reasons (i.e., writing data to the union/layered filesystem of a container has a performance penalty - writing to a volume prevents that).
>When not naming your volume you generally mean: I don't "care" about its data, it's ok to remove after the container is removed. 

It's from https://github.com/moby/moby/issues/30647, which is definitely worth a read.

**Comment by amshinde** [comment] 2019-05-07 20:21
@awprice What version of runtime are you using? I am not able to reproduce this with the latest runtime.
@egernst @mcastelino Can one of you give this a shot as well?

**Comment by awprice** [comment] 2019-05-07 23:26
We are using the following:

Runtime - https://github.com/kata-containers/runtime/releases/tag/1.7.0-alpha1
Containerd 1.2.6
Kubernetes 1.13.5

I believe you might not run into this issue if you are using Docker.

**Closed** 2019-05-09 08:38 UTC
