### ISSUE TITLE
random failures with virtiofs

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#2555] opened 2020-03-24 22:01 UTC
I have seen some random failures on the virtiofs CI, the failure is related with an unexpected /opt/kata/bin/qemu-virtiofs-system-x86_64 present. I see that most of the time happens after running the functional tests, see http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-virtiofs-PR/255/console

**Comment by jongwu** [comment] 2020-03-29 10:55
Hi @GabyCT , I know something which may related with this issue. if you run kata-runtime with virtiofs round after round , eg :
for i=0; i<10; i++ {
kata-runtime run kk
}
the round may not continue for the second because in the second round it will warn as no qmp.sock available. the root cause is that the the qemu process spawned by the first kata has not exited completely when the second kata started.
I try to debug this issue and find that if we compile the qemu without "--static", this issue will not occur. but I don't know why for now.
I can't tell if the issue I report is the identical one with yours, but can be a reference.

**Comment by jcvenegas** [comment] 2020-08-17 19:01
Seems that this issue was not seen in a while, probably need to have stress test with virtiofs to launch many times until find this kind of issues as @jongwu  points.

**Comment by jcvenegas** [comment] 2020-08-17 19:03
Closing this issue @jongwu  please open an issue if needed for the case you have seen.

**Closed by jcvenegas** 2020-08-17 19:03 UTC
Labels: bug, needs-review
