### ISSUE TITLE
Does kata plan to support checkpoint/restore?

### ISSUE THREAD

**Issue by yyyeerbo** [kata-containers/runtime#1473] opened 2019-04-03 09:34 UTC
Maybe we can use snapshot to achieve better checkpoint/restore than criu?

**Comment by devimc** [comment] 2019-04-03 13:44
cc @gnawux @egernst

**Comment by soolaugust** [comment] 2020-03-30 04:04
also want to know, 👍

**Comment by devimc** [comment] 2020-03-30 13:47
@soolaugust I don't see this in the [kata 2.0 roadmap][1]. 

[1]: https://github.com/kata-containers/kata-containers/projects/2

**Comment by soolaugust** [comment] 2020-04-02 05:38
I see. very excited if this could be supported.

**Comment by chris13524** [comment] 2020-07-04 16:14
Can't this runtime just plug into [QEMU's checkpointing feature](https://wiki.qemu.org/Features/MicroCheckpointing)?

Also noting that this issue appears to be a duplicate of #184

**Comment by devimc** [comment] 2020-07-06 14:59
@chris13524 yeah, QEMU micro checkpoints looks good, [CRIU](https://criu.org/Main_Page) should work too, maybe we can support both and let user choose the best

**Closed** 2021-04-07 09:04 UTC
