### ISSUE TITLE
namespace test failing with q35 on centos

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#1604] opened 2019-04-29 07:34 UTC
CentOS q35 CI failing:

```
=== RUN   TestHostNetworkingRequested
--- FAIL: TestHostNetworkingRequested (0.01s)
    assertions.go:239: 
                          
	Error Trace:	network_test.go:99
        
	Error:      	Should be true
```

See https://github.com/kata-containers/runtime/pull/1587.

**Comment by jodh-intel** [comment] 2019-04-29 08:47
Also seen here: https://github.com/kata-containers/runtime/pull/1599#event-2306049751.

**Comment by lifupan** [comment] 2019-04-29 12:22
Hi @jodh-intel, 

I found the root cause is that the kernel in CentOS q35 is 3.10 which doesn't support the "nsfs",
and the "nsfs" isn't supported until  3.19 version. 
I'm curious when did we add the centos q35 test? Why this failed didn't appear until recently?

**Comment by jodh-intel** [comment] 2019-04-29 12:48
Thanks @lifupan.

 The Jenkins q35 jobs were added on https://github.com/kata-containers/ci/pull/144, but I'm not sure if the date on that PR is the same as the time we actually started using them. Maybe @GabyCT can provide further info?

Rather than ignoring on centos, I think this is another use-case for https://github.com/kata-containers/runtime/pull/1587. I'll add a new call to allow skipping a test if the kernel version is too old...

**Comment by GabyCT** [comment] 2019-04-30 13:26
@jodh-intel and @lifupan , yes the day that that PR landed the CI started running for PR, the master jenkins jobs for Q35 started working before that PR as I tested that the jobs were stable

**Comment by jodh-intel** [comment] 2019-05-09 15:29
This is a duplicate of #1517.

**Closed** 2021-04-07 09:03 UTC
