### ISSUE TITLE
container_fs_writes_bytes_total never increase in kubernetes

### ISSUE THREAD

**Issue by DrmagicE** [kata-containers/runtime#2400] opened 2020-01-17 10:01 UTC
# Description of problem
I run a centos container pod and generate a test file in it with the following dd command：`dd if=/dev/zero of=test bs=10M count=20 && sync`. I expect `container_fs_writes_bytes_total` should increase after dd, but it doesn't change at all. I test the command in docker, and it works as expected.

I have set `sandbox_cgroup_only` to true.

related issue: https://github.com/kata-containers/runtime/issues/2135#issuecomment-575098740

The result of PromQL: `container_fs_writes_bytes_total{pod_name="centos-74db8d954c-p8vpb"}`
```
container_fs_writes_bytes_total{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",device="/dev/dm-0",id="/vc/kata_9b65ea542098c3d380a1e7d797c4161c6cb3da118ab5debbcf9d4e593f65275d",image="gcr.azk8s.cn/google_containers/pause-amd64:3.1",instance="x.x.x.x",job="kubernetes-nodes-cadvisor",katacontainers_io_kata_runtime="true",kubernetes_io_hostname="125.88.39.167",name="9b65ea542098c3d380a1e7d797c4161c6cb3da118ab5debbcf9d4e593f65275d",namespace="default-1003",pod_name="centos-74db8d954c-p8vpb"}  9733120
container_fs_writes_bytes_total{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",device="/dev/sda",id="/vc/kata_9b65ea542098c3d380a1e7d797c4161c6cb3da118ab5debbcf9d4e593f65275d",image="gcr.azk8s.cn/google_containers/pause-amd64:3.1",instance="x.x.x.x",job="kubernetes-nodes-cadvisor",katacontainers_io_kata_runtime="true",kubernetes_io_hostname="125.88.39.167",name="9b65ea542098c3d380a1e7d797c4161c6cb3da118ab5debbcf9d4e593f65275d",namespace="default-1003",pod_name="centos-74db8d954c-p8vpb"}
```

~Further more, the network metric `container_network_transmit_bytes_total` seems always return higher value than expected.~

Kata version:
```
kata-runtime  : 1.10.0-alpha1
   commit   : ae2a0d646207a54d1190c861fad3e964ef043937
   OCI specs: 1.0.1-dev
```
 
# Expected result
The result of the PromQL : `sum(container_fs_writes_bytes_total{pod_name="my_pod_name"})` should increase about 200M after dd. 

# Actual result
It doesn't change at all...

**Comment by grahamwhaley** [comment] 2020-01-17 10:24
/cc @devimc @amshinde 
Hmm, so, I guess that somehow the kata fs mountpoint is not being accounted for in the, err, correct cgroup/namespace somewhere?

**Comment by devimc** [comment] 2020-01-17 13:16
might be because blkio cgroup is not yet supported

**Comment by devimc** [comment] 2020-01-17 13:47
ohh wait, try again with master, I forgot #2350 was merged yesterday

**Comment by DrmagicE** [comment] 2020-01-20 02:41
@devimc Hi, I have tested with master, but unfortunately, the metric still has not changed..

**Comment by devimc** [comment] 2020-01-20 16:49
@DrmagicE which storage drive are you using?

**Comment by DrmagicE** [comment] 2020-01-21 01:34
@devimc do you mean the ` BlockDeviceDriver` ?  It is `virtio-scsi`, and we are using containerd as CRI implementation.
```
kata-runtime kata-env
[Meta]
  Version = "1.0.23"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = true
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.10.0-rc0"
    Commit = "d11696de9a21a590e3684ab2d681005c796cd507"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration-qemu.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.0\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-vanilla-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false
  SharedFS = "virtio-9p"

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.10.0-alpha1_agent_c87f497312.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.19.75.55-59.1.container"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.10.0-alpha1-3b405f7"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.10.0-alpha1-54f93db"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"
  Debug = false
  Trace = false
  TraceMode = ""
  TraceType = ""

[Host]
  Kernel = "5.3.13-1.el7.elrepo.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "CentOS Linux"
    Version = "7"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz"

[Netmon]
  Version = "kata-netmon version 1.10.0-rc0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```

**Comment by devimc** [comment] 2020-01-21 15:04
@DrmagicE are you using devicemapper or overlay2 as storage driver?

**Comment by DrmagicE** [comment] 2020-01-21 15:04
@devimc overlay2

**Comment by devimc** [comment] 2020-01-21 15:11
@DrmagicE I guess something is missing in the cgroup implementation, I need time to debug it, thanks again for raising this

**Comment by DrmagicE** [comment] 2020-02-03 01:42
@devimc Hi, is there any update?

**Comment by devimc** [comment] 2020-02-04 14:57
@DrmagicE not yet, I'm still fixing some cgroup issues, I hope one of them is causing this

**Comment by devimc** [comment] 2020-02-11 16:29
indeed, I can reproduce this issue :cry: 
@DrmagicE did you use 9p or virtio-fs?  I have a crazy theory that I'd like to confirm

**Comment by DrmagicE** [comment] 2020-03-17 13:30
@devimc sorry for the late reply.I have upgraded the kata version and tested it in a new kubernetes cluster and it work as expected. I am not sure the old one was using 9p or virtio-fs. 

And i use a new command `if=/dev/zero of=test bs=10M count=20 oflag=direct` instead of the old one, maybe you can try this one.

version info:
```
kata-runtime  : 1.11.0-alpha0
   commit   : ede05d5223030d225cbb389e061489bdb570ed5d
   OCI specs: 1.0.1-dev
```

**Comment by DrmagicE** [comment] 2020-03-18 07:54
@devimc oops..I forgot to add  `io.kubernetes.cri.untrusted-workload: "true"` annotation.. so the previous test result was related to runc, and still the metric is not increasing.  I am not familiar with 9p or virtio-fs.How can i check it is 9p or virtio-fs?

**Comment by devimc** [comment] 2020-03-23 20:52
thanks @DrmagicE , it looks like you're using 9p (`SharedFS = "virtio-9p"`) unfortunately the IO operations are not taking into account by the cgroup (I still don't know why) when 9p is used,  please consider switching to virtio-fs [1].
This issues is not reproducible with virtio-fs.

[1] - https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-virtio-fs-with-kata.md

**Comment by ariel-adam** [comment] 2020-08-18 14:24
Given that this work with virtiofs and our focus will be on virtiofs and not 9p looking forward we will close this as won't fix.

**Closed by ariel-adam** 2020-08-18 14:24 UTC
Labels: bug, needs-review
