### ISSUE TITLE
kata network doesn't work with aws vpc cni

### ISSUE THREAD

**Issue by coderplay** [kata-containers/runtime#2647] opened 2020-04-26 08:23 UTC
# Description of problem
I've been trying to evaluate the kata network in aws these days.   I setup a kubernetes cluster with [aws vpc cni](https://github.com/aws/amazon-vpc-cni-k8s). 
I created a pod with  command `iperf3 -s` as the server side and start testing pod to pod communication from another pod with command `iperf3 -c $server_pod_ip`

the $server_pod_ip is 172.31.19.188 , and host ip is 172.31.30.165 for future discussion .

# Expected result
It worked well with `runc` runtime. 

# Actual result
kata container doesn't work with aws vpc cni. I tried with `tcfilter` and `macvtap` models, none of them worked.

```
$ kubectl exec -it iperf-kata -- /bin/bash
# iperf3  -c 172.31.19.188 -O 2 -Z -P 64
iperf3: error - unable to connect to server: No route to host
```

# Root Cause

### Observation
The default `tcfilter` mode added a `tap0_kata` on container's netns and some tc filters.  
```
sudo  ip netns exec cni-58dbccb2-ed1b-ce69-1ea0-97b40f39134b tc qdisc
qdisc noqueue 0: dev lo root refcnt 2
qdisc noqueue 0: dev eth0 root refcnt 2
qdisc ingress ffff: dev eth0 parent ffff:fff1 ----------------
qdisc mq 0: dev tap0_kata root
qdisc fq_codel 0: dev tap0_kata parent :1 limit 10240p flows 1024 quantum 9015 target 5.0ms interval 100.0ms memory_limit 32Mb ecn
qdisc ingress ffff: dev tap0_kata parent ffff:fff1 ----------------
```

ARP to host worked
```
$ sudo  ip netns exec cni-58dbccb2-ed1b-ce69-1ea0-97b40f39134b  /usr/sbin/arping -I eth0 172.31.30.165
ARPING 172.31.30.165
42 bytes from 2a:71:7a:a8:9e:6b (172.31.30.165): index=0 time=9.587 usec
42 bytes from 2a:71:7a:a8:9e:6b (172.31.30.165): index=1 time=5.819 usec
42 bytes from 2a:71:7a:a8:9e:6b (172.31.30.165): index=2 time=5.716 usec
42 bytes from 2a:71:7a:a8:9e:6b (172.31.30.165): index=3 time=6.003 usec
42 bytes from 2a:71:7a:a8:9e:6b (172.31.30.165): index=4 time=5.957 usec
^C
--- 172.31.30.165 statistics ---
5 packets transmitted, 5 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 0.006/0.007/0.010/0.001 ms
```

Ping didn't work
```
$ sudo  ip netns exec cni-58dbccb2-ed1b-ce69-1ea0-97b40f39134b  ping  172.31.30.165
PING 172.31.30.165 (172.31.30.165) 56(84) bytes of data.
^C
--- 172.31.30.165 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3066ms
```

After I removed the tap device and those tc filters, the eth0 works fine from netns. I ran below command from host ,and confirmed the connectivity. 
```
ip netns exec cni-58dbccb2-ed1b-ce69-1ea0-97b40f39134b /usr/bin/iperf3 -c 172.31.19.188 -O 2 -Z -P 64
```

### How AWS VPC CNI setup an ip to a container netns
[this](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md) is the design document of  AWS VPC CNI . Below is an simulation how aws vpc cni setup an ip to a container netns

```
ip link add eni-host type veth peer name eth0  /* on host namespace */
ip netns add ns-minzhou
ip link set eth0 netns ns-minzhou  /* move eth0 to Pod's namespace ns-minzhou */
ip link set eni-host up /* bring up eni-host */
ip netns exec ns-minzhou ip link set eth0 up /* bring up eth0 in Pod's namespace ns-minzhou */

/* To assign IP address 172.31.28.93 to Pod's namespace ns-minzhou */
ip netns exec ns-minzhou ip addr add 172.31.28.93/32 dev eth0 /* assign a IP address to eth0 */
ip netns exec ns-minzhou ip route add 169.254.1.1 dev eth0 /* add default gateway */
ip netns exec ns-minzhou ip route add default via 169.254.1.1 dev eth0 /* add default route */

ip netns exec ns-minzhou arp -i eth0 -s 169.254.1.1 <eni-host's mac> /* add static ARP entry for default gateway */

/* Pod's IP address is 172.31.28.93/32 */
ip route add 172.31.28.93/32 dev eni-host /* add host route */
```

Related PR:  https://github.com/kata-containers/runtime/issues/144
Reference: https://gist.github.com/mcastelino/7d85f4164ffdaf48242f9281bb1d0f9b

Giving that Azure's vnet CNI is quite similar to AWS's, I don't think kata network could work with these two major cloud providers.

@mcastelino @amshinde @egernst  Could you please share your insights why kata's tap0 and tc filters doesn't work with the CNI setup?   I am willing to do some quick experiments if you have a fix with some commands.

**Comment by mcastelino** [comment] 2020-04-27 16:44
@coderplay I suspect the static ARP addition may be the reason for the failure. Can you try adding the static arp entry inside the container and see if that fixes the issue. We do not propagate static ARP entries today. We may need to implement static ARP propagation like we do for routes.

/cc @amshinde

**Comment by coderplay** [comment] 2020-04-27 17:56
@mcastelino thanks for the tips.  Which device's mac address should I bind to?    `<eni-host's mac>`, `eth0` in container namespace or `tap0_kata`'s? 

I've tried all 3, it's not allowed in guest VM.
```
$ kubectl exec -it iperf-kata -- /bin/bash
# ip neigh add 169.254.1.1 dev eth0 lladdr ae:fa:63:8e:49:f8
RTNETLINK answers: Operation not permitted
```

**Comment by mcastelino** [comment] 2020-04-27 18:29
Can you try with `mcastelino/iperf` and see if it works.

**Comment by mcastelino** [comment] 2020-04-27 18:30
> @mcastelino thanks for the tips. Which device's mac address should I bind to? `<eni-host's mac>`, `eth0` in container namespace or `tap0_kata`'s?

eni's host mac

**Comment by coderplay** [comment] 2020-04-27 18:42
> Can you try with `mcastelino/iperf` and see if it works.

The same result with your image. 

```
$ kubectl describe pod iperf-kata
Name:         iperf-kata
Namespace:    default
Priority:     0
Node:         ip-172-31-30-165/172.31.30.165
Start Time:   Mon, 27 Apr 2020 18:37:20 +0000
Labels:       <none>
Annotations:  Status:  Running
IP:           172.31.25.143
IPs:
  IP:  172.31.25.143
Containers:
  iperf-kata:
    Container ID:  containerd://8fac3ab839ff4bd06f38e6d0dbbee2fe5a76797de5d0aa888e883c883bc02a52
    Image:         mcastelino/iperf
    Image ID:      sha256:879876bbdef87811ce2d88a23af4d5417f6d8b431513023463ecac4fd916b140
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sleep infinity
    State:          Running
      Started:      Mon, 27 Apr 2020 18:37:28 +0000
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: Timeout reached after 3s waiting for device 0:0:0:28/block: context deadline exceeded
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 00:00:00 +0000
      Finished:     Mon, 27 Apr 2020 18:37:25 +0000
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6xdz4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-6xdz4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6xdz4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                       Message
  ----     ------     ----               ----                       -------
  Normal   Scheduled  17s                default-scheduler          Successfully assigned default/iperf-kata to ip-172-31-30-165
  Warning  Failed     12s                kubelet, ip-172-31-30-165  Error: failed to create containerd task: Timeout reached after 3s waiting for device 0:0:0:28/block: context deadline exceeded
  Normal   Pulling    11s (x2 over 16s)  kubelet, ip-172-31-30-165  Pulling image "mcastelino/iperf"
  Normal   Pulled     11s (x2 over 16s)  kubelet, ip-172-31-30-165  Successfully pulled image "mcastelino/iperf"
  Normal   Created    11s (x2 over 15s)  kubelet, ip-172-31-30-165  Created container iperf-kata
  Normal   Started    9s                 kubelet, ip-172-31-30-165  Started container iperf-kata
```



```
$ kubectl exec -it iperf-kata -- /bin/bash
root@iperf-kata:/# ip neigh add 169.254.1.1 dev eth0 lladdr 6a:92:3a:59:70:aa
root@iperf-kata:/# ping www.google.com
PING www.google.com (172.217.7.196): 56 data bytes
64 bytes from 172.217.7.196: icmp_seq=0 ttl=50 time=1.287 ms
64 bytes from 172.217.7.196: icmp_seq=1 ttl=50 time=1.498 ms
64 bytes from 172.217.7.196: icmp_seq=2 ttl=50 time=1.371 ms
64 bytes from 172.217.7.196: icmp_seq=3 ttl=50 time=1.382 ms
^C--- www.google.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 1.287/1.385/1.498/0.075 ms
root@iperf-kata:/# iperf3 -c 172.31.19.188
Connecting to host 172.31.19.188, port 5201
iperf3: error - unable to create a new stream: No such file or directory
```

It might be other issues with kata runtime.

**Comment by devimc** [comment] 2020-04-27 19:54
just out of curiosity, is `sandbox_cgroup_only` on?

**Comment by coderplay** [comment] 2020-04-27 20:03
@devimc nope,  I didn't change any kata configurations.  By default, it's false.

```
$ cat  /etc/kata-containers/configuration.toml | grep sandbox_cgroup_only
sandbox_cgroup_only=false
```

**Comment by coderplay** [comment] 2020-04-27 20:08
Another observation:  `apt-get update` was stuck.

**Comment by coderplay** [comment] 2020-04-27 21:29
I hacked iperf3 source, and made it work.

**Comment by amshinde** [comment] 2020-04-27 21:46
@coderplay Yes,  we have seen this issue with 9p earlier. We have had to use tricks such as `mount -t ramfs -o size=20M ramfs /tmp; iperf3 -c 192.168.0.12`  in the past.
We plan to use `virtio-fs` file-system going forward as a replacement for 9p going forward. Can you try this out with using `virtio-fs` instead.

**Comment by amshinde** [comment] 2020-04-27 21:56
@coderplay For the ping issue, we do need to propagate the static ARP entries for the tap interface. I am trying to reproduce this issue myself now. 
I did start an AWS i3 metal instance and setup k8s manually with the aws-vpc-cni. But I am seeing some failures to begin with:
```kubectl logs aws-node-86jzq -n kube-system
Starting IPAM daemon in the background ... ok.
ERROR: logging before flag.Parse: E0427 21:31:32.109858       6 memcache.go:147] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable
to handle the request
```
Looking closely at the CNI daemonset, I am seeing this:
```
- name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: dockershim
          hostPath:
            path: /var/run/dockershim.sock
```
Which makes me question if/how this CNI supports other CRI such as containerd/crio.
Can you provide steps for your setup?

**Comment by coderplay** [comment] 2020-04-27 22:06
@amshinde did you create a IAM role and with a proper policy on it, and created instance with that IAM role?

**Comment by coderplay** [comment] 2020-04-27 22:21
> @coderplay Yes, we have seen this issue with 9p earlier. We have had to use tricks such as `mount -t ramfs -o size=20M ramfs /tmp; iperf3 -c 192.168.0.12` in the past.
> We plan to use `virtio-fs` file-system going forward as a replacement for 9p going forward. Can you try this out with using `virtio-fs` instead.
> 
> You can take a look at this guide: https://github.com/kata-containers/documentation/blob/d89db1740770947bc947800764fe81a29306523b/how-to/how-to-use-virtio-fs-with-kata.md

Thanks for the info, @amshinde !  I also observed that iperf3 get 2.7 GBytes/s with my settings, and get only 170 Mbytes/s in iperf3 zero copy mode which under the neath is `sendfile`.    It might be also due to 9p?  Let me try out.

**Comment by mcastelino** [comment] 2020-04-27 22:24
@amshinde we need to support at least initial ARP mirroring. I assume the CNI will not update it once setup.

**Comment by amshinde** [comment] 2020-04-27 22:27
@coderplay Yes, I did create a similar policy after I ran into issues with dowloading the image used by the CNI and set that as the policy for the already running instance. But still seeing the metrics related issues.
Did you setup k8s manually or used `kops` for the setup? 
Also, I saw that the CNI was using the `docker.sock` and `dockershim.sock` by passing them as mounts, so I had my doubts how the CNI supports other CRI layers.

**Comment by coderplay** [comment] 2020-04-27 22:35
I setup k8s with kubeadm, and didn't see issues. Looks like it's a k8s metrics server reachability issue similar to this?  https://github.com/kubernetes-sigs/metrics-server/issues/157   

I created a two nodes k8s cluster, one is master, another one is a i3.metal worker node. They are under a security group allows all internal traffic.

**Comment by coderplay** [comment] 2020-04-27 22:38
I just tried with `mount -t ramfs -o size=20M ramfs /tmp; iperf3 -c 192.168.0.12`,  confirmed that the 170 Mbytes/s slow throughput with zero copy was because of the `9p` filesystem

**Comment by amshinde** [comment] 2020-04-28 05:14
@coderplay Thanks for verifying. I was able to reproduce your issue. Turns out I needed to restart the AWS instance for the IAM role to take effect. Will send out a fix to mirror the arp entries.

**Comment by coderplay** [comment] 2020-04-28 05:33
Thanks for the quick response @mcastelino @amshinde !

**Comment by amshinde** [comment] 2020-08-25 17:06
The fix has been merged. Closing this.

**Closed by amshinde** 2020-08-25 17:06 UTC
Labels: bug, needs-review
