### ISSUE TITLE
mount blockdevices in the guest VM

### ISSUE THREAD

**Issue by zklei** [kata-containers/runtime#881] opened 2018-11-03 08:58 UTC
# Description of problem
When we use `docker run -v /dev/sdb:/mnt/data ` to run a container, It will passing `/dev/sdb/` through as blockdevice `/mnt/data`. 

# Expected result
Usually, What we want is to mount the block device as a directory in container, Or we're going to choose --device to pass this blockdevice.

**Comment by WeiZhang555** [comment] 2018-11-05 01:44
Duplicate of #571

**Closed** 2021-04-07 09:05 UTC
