### ISSUE TITLE
make DESTDIR=/foo install is not honored. 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#401] opened 2018-06-14 23:47 UTC
# Description of problem
When `make install DESTDIR=/tmp/dest` is used not all is installed in `/tmp/dest`

# Expected result
Install all under `/tmp/dest`

# Actual result

```
tree /tmp/dest/
/tmp/dest/
└── usr
    ├── bin
    │   └── kata-collect-data.sh
    └── share
        └── defaults
            └── kata-containers
                └── configuration.toml
```
---

**Comment by WeiZhang555** [comment] 2018-06-15 02:54
Duplicate of https://github.com/kata-containers/runtime/issues/337

I don't have strong opinion on removing it or making it work.

**Comment by WeiZhang555** [comment] 2018-06-15 02:55
Let me close this and discuss more in previous thread #337

**Closed** 2018-06-15 02:56 UTC
Labels: duplicate
