### ISSUE TITLE
metrics CI job is failing, blocking issue merging

### ISSUE THREAD

**Issue by c3d** [kata-containers/runtime#2983] opened 2020-09-23 13:54 UTC
# Description of problem

Some PRs, like for example https://github.com/kata-containers/runtime/pull/2891, are blocked due to the CI failing. The jenkins-metrics-ubuntu-18-04 job is failing, and this is not directly related to these CRs.

Example of failure: http://jenkins.katacontainers.io/job/kata-metrics-runtime-ubuntu-18-04-PR/2069/console.
```
14:26:49 Report Summary:
14:26:49 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
14:26:49 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG  | COV  | ITS |
14:26:49 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
14:26:49 | P   | boot-times           | 95.0% | 101.8% | 105.0% | 10.0% | 94.6%  | 117.6% | 24.3% | 4.5% |  20 |
14:26:49 | *F* | memory-footprint     | 95.0% | 106.4% | 105.0% | 10.0% | 106.4% | 106.4% | 0.0%  | 0.0% |   1 |
14:26:49 | P   | memory-footprint-ksm | 95.0% | 100.2% | 105.0% | 10.0% | 100.2% | 100.2% | 0.0%  | 0.0% |   1 |
14:26:49 | P   | blogbench            | 90.0% | 103.4% | 110.0% | 20.0% | 103.4% | 103.4% | 0.0%  | 0.0% |   1 |
14:26:49 | P   | blogbench            | 90.0% | 103.5% | 110.0% | 20.0% | 103.5% | 103.5% | 0.0%  | 0.0% |   1 |
14:26:49 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
14:26:49 Fails: 1, Passes 4
```

# Expected result

CI metric repaired, or root cause for it failing repaired, so as to not block independent PRs.

# Actual result

PRs that have no direct impact on that metric are blocked.

# Further information

I have searched for any issue containing "metrics" and did not find any.

**Comment by devimc** [comment] 2020-09-23 13:56
@GabyCT is working on this - issue https://github.com/kata-containers/tests/issues/2839

**Comment by c3d** [comment] 2020-09-24 07:54
@GabyCT I assigned this one to you, since @devimc pointed out you were working on it. Please feel free to close as a duplicate if you think it's the same thing. Thanks.

**Comment by c3d** [comment] 2020-09-24 09:33
@jodh-intel I propose to add a new temporary flag, "blocked-by-metrics", to flag PRs that are blocked by this.

**Comment by GabyCT** [comment] 2020-09-24 15:29
It looks like https://github.com/kata-containers/packaging/commit/3d2bb461eab80fe5a1f61ea96ced8c27451fb7e7 introduced the regression

**Comment by GabyCT** [comment] 2020-09-24 20:10
To increase memory limits PR https://github.com/kata-containers/tests/pull/2840

**Comment by GabyCT** [comment] 2020-09-24 21:50
The PR got merged this issue should be resolved now

**Closed by GabyCT** 2020-09-24 21:50 UTC
Labels: blocked-by-metrics, bug, needs-review

**Comment by amshinde** [comment] 2020-09-24 22:05
@c3d We will need to rerun the metrics job for the pending PRs with /test-ubuntu-qemu-metrics command.
