### ISSUE TITLE
Issues with memory constraints

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#483] opened 2018-07-12 20:55 UTC
While running a container with a memory constraint, I found that the amount of memory that we are able to use is really small. In the following example I am assigning a container a memory of 256m and using only 100m and the result is that the container is running out of memory
```
$ docker run --runtime kata-runtime --rm -m 256m debian perl -e 'my $name = " "x1024x1024x100;'                                 
Out of memory!
```
If I look inside the container, it says that I have the following amount of memory
```
$ docker run -ti --runtime kata-runtime -m 256m debian bash
root@384678345bcd:/# cat /proc/meminfo
MemTotal:         242348 kB
MemFree:          207196 kB
MemAvailable:     207228 kB
```
While doing the same with runc the issue is not present
```
$ docker run --runtime runc --rm -m 256m debian perl -e 'my $name = " "x1024x1024x250;'
```

This is the configuration that I am using
kata-runtime  : 1.1.0
commit   : ff7b4f6ed7f622217f456a9215f5e7c6215ff916
OCI specs: 1.0.1
kata-agent version 1.1.0-17b44df35a174c09966cf9d2ccc8472a597feda1
kata-proxy version 1.1.0-7e2a93d1931d814debfcff2846b1514af1b9601d
kata-shim version 1.1.0-6ddca0334d0e8dee6e1e00f0c120fde4b8c1c176
Docker version 18.03.1-ce, build 9ee9f40

**Comment by grahamwhaley** [comment] 2018-07-13 09:36
Let's get a couple more bits of info...
- can you get the `/proc/meminfo` for the `runc` case as well, for comparison. Or maybe better a `free` for both, which might give just just a little more detail.
- And then, what does that `free` look like in the `runc` case after the perl allocation has worked. I'd like to check just how much memory that `perl` line is allocating - I don't know the internals of `perl`, but it is not going to surprise me if that line costs more than 100m in reality.

And, just FMI so we can compare and think about this - how and where does a memory constraint get applied to a Kata VM (I've not been tracking it...) - that will affect our expected outcome here I think.

**Comment by GabyCT** [comment] 2018-07-13 15:57
For `runc` here it is the information of `/proc/meminfo`

```
$ cat /proc/meminfo
MemTotal:       16312552 kB
MemFree:        15014576 kB
MemAvailable:   15774300 kB
```

Here it is the information for `runc` with `free`

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        145M         14G         21M        1.1G         15G
Swap:           15G        1.0M         15G
```

Now for `kata-runtime`

Here it is the information with `free`

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           236M         14M        204M        1.7M         18M        204M
Swap:            0B          0B          0B
```

**Comment by grahamwhaley** [comment] 2018-07-13 16:02
Ooh, OK - and what is that telling us ;-) - I suspect it means more digging and info is required...

runc is I think going to be using a memory cgroup - which looks like it does not show up in meminfo or free - so can you look into how (if) you can see what the memory cgroup limits are, and if it can report what is used so far - that will them make that data a more 'fair measure and comparison' with our VM memory settings.
Also, can you look at the memory before/after you run the perl test so we can tell how much memory that test is actually consuming (under runc is fine) - which might help us figure out why we have failed the test in the VM.

**Comment by GabyCT** [comment] 2018-07-17 16:09
Here it is the information for `kata-runtime`
```
root@2b71d8cb99f5:/sys/fs/cgroup/memory# cat memory.limit_in_bytes
9223372036854771712
```
Here it is the information for `runc`
```
root@be9ce8320fef:/sys/fs/cgroup/memory# cat memory.limit_in_bytes
268435456
```

**Comment by GabyCT** [comment] 2018-07-17 16:33
Here it is the information
```
$ docker exec 8471a277b4be bash -c "smem"
  PID User     Command                         Swap      USS      PSS      RSS
    1 root     bash                               0     1400     1613     2024
 2119 root     perl -e my $name = " "x1024        0    11268    11671    12272
```

**Comment by devimc** [comment] 2018-07-20 15:39
it's an expected behaviour since perl consume twice memory, you can reproduce it in runc

```sh

# Check memory before running the container
$ cat /proc/meminfo | grep MemAvailable && free -h
MemAvailable:   15555072 kB
              total        used        free      shared  buff/cache   available
Mem:            15G        293M         11G        1.6M        3.8G         14G
Swap:          4.0G        768K        4.0G

# "Allocate 40MB using perl"
$ docker run --rm -dti -m 50MB --runtime=runc --name test debian perl -e 'my $v=" "x1024x1024x40; sleep'

# Check free memory
$ cat /proc/meminfo | grep MemAvailable && free -h
MemAvailable:   15472808 kB
              total        used        free      shared  buff/cache   available
Mem:            15G        373M         11G        1.6M        3.8G         14G
Swap:          4.0G        768K        4.0G
```

```
(15555072−15472808)/1024 = 80.33 MB
```

the question here is why docker/runc doesn't kill the process?

feel free to close this issue if you want  :smile:

**Comment by grahamwhaley** [comment] 2018-07-20 15:41
Thanks @devimc! I suspect I might know why docker/runc does not kill the process off... let me see if I can find a reference...

**Comment by grahamwhaley** [comment] 2018-07-20 15:46
hmm, and I thought it might be a 'softish' limit - but, not according to the docker docs:
https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory
If we wanted to dig, then I think we'd want to figure out where the memory actually went...
- is it in the process
- is it actually allocated (backed). I'm not sure that perl line actually writes to the whole of that array does it?

Scope for digging and understanding here if somebody wants to ...

**Comment by devimc** [comment] 2018-07-20 15:51
please don't use perl for memory tests, instead you can use `vish/stress`

```
docker run --rm -ti -m 256MB --runtime=kata-runtime --name test vish/stress -mem-total 40M
```

**Closed** 2018-07-23 16:41 UTC
