### ISSUE TITLE
kata-runtime not support

### ISSUE THREAD

**Issue by LinshanYu** [kata-containers/runtime#2819] opened 2020-07-09 01:11 UTC
# Description of problem

Integrate kata into k8s failed ：Open crio on mgt01 (master0), then kubectl get runtimeclass can see kata-runtime; at this time I create a pod who's runtimeclassname is kataruntime, and nodename is mgt01，  describe pod: Failed create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "kata-runtime" not supported.
apiVersion: v1
kind: Pod
metadata:
  name: kata-pod-yls
spec:
  runtimeClassName: kata-runtime
  containers:
    - name: kata-pod-yls
      image: docker.io/alpine
      tty: true
  nodeName: mgt01    

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result
Can't create the pod
env:
{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"$Format:%H$", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liubin** [comment] 2020-07-13 09:22
Hi @LinshanYu , can you share with us  the output of `kubectl get runtimeclass -o yaml` ?

**Comment by LinshanYu** [comment] 2020-07-14 00:48
> runtimeclass
apiVersion: node.k8s.io/v1beta1
handler: kata-runtime
kind: RuntimeClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"node.k8s.io/v1beta1","handler":"kata-runtime","kind":"RuntimeClass","metadata":{"annotations":{},"name":"kata-runtime"}}
  creationTimestamp: "2020-07-08T02:04:11Z"
  name: kata-runtime
  resourceVersion: "76742223"
  selfLink: /apis/node.k8s.io/v1beta1/runtimeclasses/kata-runtime
  uid: 50aba570-c0bf-11ea-ac84-525400a630d9

**Comment by liubin** [comment] 2020-07-14 01:35
Hi @LinshanYu ,  how did you setup your K8s cluster? Did you referenced https://github.com/kata-containers/documentation/tree/master/how-to#kubernetes-integration . 

You should also configure containerd or cri-o to run Kata containers.

**Comment by ariel-adam** [comment] 2020-09-08 14:10
The issue is missing information and has not been active for 2 month (pending a reply from LinshanYu).
We are closing the issue for now.
LinshanYu, please feel free to open it if it is still and issue and you can continue providing us with the relevant information.

**Closed by ariel-adam** 2020-09-08 14:10 UTC
Labels: bug, needs-review

**Comment by jodh-intel** [comment] 2020-09-08 14:13
If you do need to re-open, please run the command specified in the issue template and paste the output here (after you have checked to ensure there is no private/sensitive information in it):

```sh
$ sudo kata-collect-data.sh
```
