### ISSUE TITLE
Hook implementation needs to be moved from virtcontainers into the CLI itself

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#273] opened 2018-04-27 23:27 UTC
Hooks are an OCI specific construct and should live in the CLI itself. 
The json that OCI expects to be passed with hooks (https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#state) is :
```
{
    "ociVersion": "0.2.0",
    "id": "oci-container1",
    "status": "running",
    "pid": 4422,
    "bundle": "/containers/redis",
    "annotations": {
        "myKey": "myValue"
    }
}
```

ociVersion, bundle and the status are all very OCI specific. Right now we just pass the pid of the process, in order to support the other fields cleanly, hooks need to be implemented and called from the CLI.

The pre-start hooks are currently called from network.go in virtcontainers, so that docker can create the veth pair that the VM uses.  For hooks to be called from CLI, we need the network to be hotplugged.
That way the VM can be created first without any network, CLI can then call the pre-start hooks with the context of a container(rather than a sandbox in VC). Docker will setup the veth for us, which can then be passed to the running VM with the help of network hotplug support.

**Comment by caoruidong** [comment] 2018-08-30 15:13
We have a new issue https://github.com/kata-containers/runtime/issues/599, could this be closed?

**Comment by caoruidong** [comment] 2018-09-11 09:07
Duplicate of #599 . Closing

**Closed** 2018-09-11 09:06 UTC
