### ISSUE TITLE
kata how to allocate swap space

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#2641] opened 2020-04-24 10:41 UTC
**Which feature do you think can be improved?**

I didn't find any kata swap related documents. What should I do if I want to allocate a 2G swap kata container?

![image](https://user-images.githubusercontent.com/14852402/80203730-386bf800-865a-11ea-9243-b8de8adae0a4.png)

**How can it be improved?**

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by grahamwhaley** [comment] 2020-04-24 10:45
I don't think it's something we come across or are asked about too often with Kata @free2k .
How are you running your container? For instance, afaik, k8s nodes are not supported with swap, so for k8s I suspect having swap available is not 'natural'.
For docker however, afaik there are options to allow swap. Tell us more about what you are trying to do and with what setup.

**Comment by devimc** [comment] 2020-04-24 12:12
this is an interesting one, this is possible by modifying the osbuilder and agent, but before that, please tell us why you need a swap? :smile_cat:

**Comment by free2k** [comment] 2020-06-17 03:06
> this is an interesting one, this is possible by modifying the osbuilder and agent, but before that, please tell us why you need a swap? 😸

I don’t want to use OOM to exit because there is not enough memory. If there is swap space, this situation can be avoided.

**Comment by free2k** [comment] 2020-06-17 03:08
Is "enable_swap = true" in the /usr/share/defaults/kata-containers/configuration.toml configuration file the option to open swap? But I have changed it to true, but the swap space is still 0

**Comment by devimc** [comment] 2020-06-17 17:24
> I don’t want to use OOM to exit because there is not enough memory. If there is swap space, this situation can be avoided.

a container that consumes more memory than the assigned... :thinking: , that could be prone to errors and/or unexpected behaviours

`enable_swap = true` is just to enable or disable memory pages swapping (qemu -runtime mlock=on|off) -  so I think the option name  for such feature is not correct.
fyi this option was added long time ago, see https://github.com/clearcontainers/runtime/commit/448ada333d914ed2ea3bbbe107ada6bd4b03a032

**Comment by amshinde** [comment] 2020-06-17 21:46
@devimc You are right, we should probably rename that to avoid confusion, `enable_swap` is essentially used to prevent the host from reclaiming memory. 
@devimc I also came accross this https://www.qemu.org/docs/master/system/deprecated.html
`The -realtime mlock=on|off argument has been replaced by the -overcommit mem-lock=on|off argument.`
We should look at the features in that list that have been deprecated in qemu 5.0 and make sure we fix govmm package to account for those changes.

Coming back to this issue, @free2k having swap memory is discouraged for k8s, and may result in incorrect resource accounting as well.  A process trying to consume more memory than it should, is typically OOMed.

**Comment by free2k** [comment] 2020-06-18 07:15
Wrong resource billing will indeed occur. This reminds me of another problem. The resource occupied by the default virtual machine is 1cpu 2G mem. Will it be affected if the memory is changed to 512M? After testing, it was found that there is no difference between allocating 2G memory and 512M memory to the virtual machine.
@amshinde @devimc

**Comment by devimc** [comment] 2020-06-18 13:54
> Will it be affected if the memory is changed to 512M? After testing, it was found that there is no difference between allocating 2G memory and 512M memory to the virtual machine.

it depends on your configuration and environment, it works with 512M because you didn't hotplug any NIC or GPU vfio device and your workload doesn't consume too much memory, having said that, it's up to you calculate the pod overhead and take it into account or not

**Comment by ariel-adam** [comment] 2020-11-03 15:29
After discussing we feel we don't want to support using swap memory in the guest.
Closing this issue, feel free to open it if you see things differently.

**Closed by ariel-adam** 2020-11-03 15:29 UTC
Labels: enhancement, needs-review
