### ISSUE TITLE
kata container fail to start

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#330] opened 2018-05-22 03:21 UTC
# Description of problem

I test container with [pouch](https://github.com/alibaba/pouch), a container engine like moby.
Start a kata container with a clean cgroup path which has no child directory, it will fail
```
#pouch run --runtime=kata-runtime --cgroup-parent=pouchnew -d registry.hub.docker.com/library/busybox:latest top
Error: failed to run container 7bed8a: {"message":"failed to create task, container id: 7bed8a3cb4372b7bc85797a0fc8ac901917e2f981e0c3e29f0d66c90407b8d20: OCI runtime create failed: write /sys/fs/cgroup/cpu/pouchnew/7bed8a3cb4372b7bc85797a0fc8ac901917e2f981e0c3e29f0d66c90407b8d20/tasks: no space left on device: unknown"}

```

# Expected result

container fails to start

# Actual result

Start container successful

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by devimc** [comment] 2018-05-22 12:21
I think this error is not related to cpuset

*no space left on device: unknown*

@Ace-Tang can you include kata-proxy logs?

**Comment by jodh-intel** [comment] 2018-05-22 12:31
... or paste in the output of `kata-collect-data.sh`, as the issue template requests :smile:

**Comment by Ace-Tang** [comment] 2018-05-22 13:11
Hi, @devimc , I make a test to verify this.
```
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset]
#mkdir test
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset]
#cd test/
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#cat cpuset.cpus 

[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#cat cpuset.mems 

[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#echo 0 > tasks 
bash: echo: write error: No space left on device
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#echo 0-31 > cpuset.cpus
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#echo 0 > cpuset.mems
[root@t100081183061.et15sqa /sys/fs/cgroup/cpuset/test]
#echo 0 > tasks 
```

**Comment by Ace-Tang** [comment] 2018-05-22 13:11
Here is the runtime log
```
time="2018-05-22T21:10:52.251942181+08:00" level=info msg="QMP details" arch=amd64 name=kata-runtime pid=17046 qmp-capabilities= qmp-major-version=2 qmp-micro-version=1 qmp-minor-version=9 source=virtcontainers subsystem=qemu
time="2018-05-22T21:10:52.252476866+08:00" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 name=kata-runtime pid=17046 source=virtcontainers subsystem=qmp
time="2018-05-22T21:10:52.254918258+08:00" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=17046 source=virtcontainers subsystem=qmp
time="2018-05-22T21:10:52.255400926+08:00" level=info msg="VM started" arch=amd64 name=kata-runtime pid=17046 sandbox-id=f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828 source=virtcontainers subsystem=sandbox
time="2018-05-22T21:10:52.256112566+08:00" level=info msg="proxy started" arch=amd64 name=kata-runtime pid=17046 proxy-pid=17152 proxy-url="unix:///run/vc/sbs/f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828/proxy.sock" sandbox-id=f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828 source=virtcontainers subsystem=kata_agent
time="2018-05-22T21:10:53.268414081+08:00" level=info msg="device details" arch=amd64 container-id=f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828 device-major=0 device-minor=214 mount-point=/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828/rootfs name=kata-runtime pid=17046 sandbox-id=f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828 source=virtcontainers subsystem=container
time="2018-05-22T21:10:53.331725045+08:00" level=info msg="path mounted" command=create name=kata-runtime path=/sys/fs/cgroup/memory pid=17046 source=runtime type=cgroup
time="2018-05-22T21:10:53.332470337+08:00" level=info msg="path mounted" command=create name=kata-runtime path=/sys/fs/cgroup/cpu pid=17046 source=runtime type=cgroup
time="2018-05-22T21:10:53.332959219+08:00" level=info msg="path not mounted" command=create name=kata-runtime path=/sys/fs/cgroup/pids pid=17046 source=runtime type=cgroup
time="2018-05-22T21:10:53.333363051+08:00" level=info msg="path mounted" command=create name=kata-runtime path=/sys/fs/cgroup/blkio pid=17046 source=runtime type=cgroup
time="2018-05-22T21:10:53.334421457+08:00" level=error msg="write /sys/fs/cgroup/cpu/newnew/f070acfa3682e5eefcc2c14ee5aaefa16e9811bd76c8866ea7c597fbc0d0c828/tasks: no space left on device" command=create name=kata-runtime pid=17046 source=runtime
```

**Comment by Ace-Tang** [comment] 2018-05-23 11:19
Hi,  @devimc @jodh-intel  , I also test kata-runtime with docker, and get the same error.

Create a container use a default cgroup parent is successful
```
[root@t100081183061.et15sqa /home/huamin.thm]
#docker run --runtime=kata-runtime -d 719f2024853e top
0b5a763491ba3e286b637d66eeabe10c5fec141ea75d554e8be1c3254b42146e
```
But create a kata container with a clean cgroup will fail
```
[root@t100081183061.et15sqa /home/huamin.thm]
#docker run --runtime=kata-runtime --cgroup-parent=cleancgroup -d 719f2024853e top
1d1b129bdc47b16ec4a807ccd230254446d01181701cd31234f292b4f4efdf23
docker: Error response from daemon: oci runtime error: write /sys/fs/cgroup/cpu/cleancgroup/1d1b129bdc47b16ec4a807ccd230254446d01181701cd31234f292b4f4efdf23/tasks: no space left on device.
```

**Comment by devimc** [comment] 2018-05-23 14:16
@Ace-Tang  create a container with a clean cgroup works for me

```
$ docker run --runtime=kata-runtime --cgroup-parent=cleancgroup -ti debian bash
root@889f703275d0:/#
$ docker run --runtime=kata-runtime --cpus=4 --cgroup-parent=cleancgroup -ti debian cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_*
100000
400000
```



am I doing something different?

**Comment by Ace-Tang** [comment] 2018-05-24 02:10
Hi, @devimc , the `cleancgroup` should never have container created before,
and  here is my docker and kata-runtime version
```
# docker version 
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

# kata-runtime -v
kata-runtime  : 0.3.0
   commit   : 2245e67f934edaa2d410384b29ab07cca305f363
   OCI specs: 1.0.1

```

**Comment by Ace-Tang** [comment] 2018-09-11 09:04
@devimc , actually I get this problem again, 
```
#docker run -d --runtime=kata-runtime reg.docker.alibaba-inc.com/ali/os:7u2
26ba566546462a4fb36ee60b32c1b2402e27e7ff0abe1e71aea090359b4ef239
docker: Error response from daemon: oci runtime error: write /sys/fs/cgroup/cpu/docker/26ba566546462a4fb36ee60b32c1b2402e27e7ff0abe1e71aea090359b4ef239/tasks: no space left on device.
```
if you do not mind, can you show me the value under `#cat /sys/fs/cgroup/cpu/docker/cpuset.cpus `.
I found mine is empty that why this creating fail.
```
#cat /sys/fs/cgroup/cpu/docker/cpuset.cpus 


```

**Comment by devimc** [comment] 2018-09-11 12:42
@Ace-Tang sorry I don't have access to `reg.docker.alibaba-inc.com/ali/os:7u2` could you please try to reproduce it with another public image?

**Comment by devimc** [comment] 2019-05-03 19:25
@Ace-Tang can we close this?

**Closed as completed** 2019-05-06 08:09 UTC
