### ISSUE TITLE
[RFC] [Proposal] support cgroups in the host

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#1125] opened 2019-01-14 19:22 UTC
# Description of the problem

Unlike other runtimes, kata starts at least 2 processes per POD, kata-shim and a hypervisor (and kata-proxy when vsocks is disable). From host perspective, containers run in a guest (virtual machine) whose resources can be monitored by monitoring the hypervisor process and its threads. kata-shims are used to interact with the containers, sending signals, reading/writing data, etc. A POD can have any number of containers that run in the same guest. One of the major gaps that can be found in kata containers currently is that cgroups are applied in the guest, but not in the host or not in the right cgroup path (see https://github.com/kata-containers/runtime/issues/1021) causing problem in some implementations for resource governance, like service fabric https://github.com/Microsoft/service-fabric/.

# Proposal

Move kata-shim (pause workload) and hypervisor (and kata-proxy if vsocks is disable) to sandbox cgroup, and apply a cgroup constraint to the sandbox that is defined by the sum of all its containers' cgroups. Container's cgroups are still created and applied but just to the kata-shim that interact with the container. 2 examples:
  
A pod with 2 containers,  container A with 1 cpu and container B without cpu constraints (1 vcpu is hotplugged).
  * in the host: no cpu constraints for container B and sandbox, 1 cpu for container A.
  * in the guest: no cpu constraints for container B, 1 cpu for container A.

A pod with 2 containers, container A with 1 cpu and container B with 2 cpus (3 vcpus are hotplugged).

![proposal-cgroups](https://user-images.githubusercontent.com/13009432/51135337-6039a280-17ff-11e9-9f30-b33df449aead.png)

**cgroup directory hierarchy**

```
/sys/fs/cgroup/cpu,cpuacct
└── kubepods/burstable/pod644e04f3
      ├── crio-89e60b84  # Sandbox cgroupsPath=/kubepods/burstable/pod644e04f3/crio-89e60b84
      ├── crio-2a95e0f8  # Container A cgroupsPath=/kubepods/burstable/pod644e04f3/crio-2a95e0f8
      └── crio-d037bce7  # Container B cgroupsPath=/kubepods/burstable/pod644e04f3/crio-d037bce7
```

cc @WeiZhang555 @mocolic

**Comment by jcvenegas** [comment] 2019-01-14 22:18
This is related to https://github.com/kata-containers/runtime/issues/878 that is looking to apply cpuset on the host at least to qemu for performance and isolation requirements. 

I like the overview of this issue to consider shim and proxy too. Also in this issue you are considering any cgroup type right ?

**Comment by jcvenegas** [comment] 2019-01-14 22:48
@devimc good, this may overlap with #878, let me see what operations k8s to on static policy and let you know but I suspect I'll be implementing the qemu cgroup cpuset part.

**Comment by WeiZhang555** [comment] 2019-01-15 02:08
What's the detailed cgroup hirarchy of your implementation? Can you give me an overview of the directory hirarchy? @devimc

**Comment by devimc** [comment] 2019-01-15 13:56
@WeiZhang555 updated, thanks

**Comment by WeiZhang555** [comment] 2019-01-16 02:59
```
/sys/fs/cgroup/cpu,cpuacct
└── kubepods/burstable/pod644e04f3
      ├── crio-89e60b84  # Sandbox cgroupsPath=/kubepods/burstable/pod644e04f3/crio-89e60b84
      ├── crio-2a95e0f8  # Container A cgroupsPath=/kubepods/burstable/pod644e04f3/crio-2a95e0f8
      └── crio-d037bce7  # Container B cgroupsPath=/kubepods/burstable/pod644e04f3/crio-d037bce7
```

So "qemu", "kata-proxy" and "kata-shim" process for "pause" container will be put in `crio-89e60b84` dir,   `kata-shim` for container A is put in `crio-2a95e0f8`, `kata-shim` process for container B is put in `crio-2a95e0f8`, am I right?

There're some missing details we need to consider, real use case is usually far more complicated.

**1. `pause` container have no constraint in general**

```
A pod with 2 containers, container A with 1 cpu and container B without cpu constraints (1 vcpu is hotplugged).

in the host: no cpu constraints for container B and sandbox, 1 cpu for container A.
in the guest: no cpu constraints for container B, 1 cpu for container A.
```

In general, the infra container(pause) container will have no CPU constraint, so in K8S, I guess in all cases, the sandbox won't have a constraints in your design, AKA qemu won't have a constraint. If so, is this cgroup support really meaningful？

** 2. "vcpu" better have a seperate dir **

In my previous design, vcpu has a standalone dir containing only the vcpu thread in qemu, IO emulator thread isn't there, this dir hirarchy is from libvirt implementation. That's because in my previous test, when doing network/file IO requests with small chunks, it consumes a lot of CPU, for a 2 CPU qemu, it requires 3 CPU to get a best performance(2 CPU for vcpu threads and 1 CPU for qemu IO emulator), if we constraint it to 2 CPU beause it has 2 vcpu, normally we can only get a 66% performance. 
I care about performance a lot.

In a word, your design can help to make existing metric tools work, that's good. But the problem is, either it can't give us a real meaningful result, or it can bring some performance influence. So we should do it very carefully, and should do more tests to see if it really works like what we want.

**Comment by WeiZhang555** [comment] 2019-01-17 02:12
> No, the sandbox won't have constraints only if there is a container without constraints, otherwise the sandbox constraints (qemu and its threads) will be equal to sum of all containers' constraints

I mean, in general, for a K8s Pod with 2 workload container, the pod is usually composed of 3 containers. 1 infra(pause) container with 2 workload container. In most(maybe all?) cases, infra container won't have a constraint, 2 workloads container will have. 

Do you mean when you set the sandbox contraint, you don't count "infra" container in? Will be sandbox resources equal to sum of 2 workload containers without "infra" container?

@devimc

**Comment by devimc** [comment] 2019-01-17 13:40
@WeiZhang555 

> Do you mean when you set the sandbox contraint, you don't count "infra" container in? 

no, because sandbox containers never have constraints

> Will be sandbox resources equal to sum of 2 workload containers without "infra" container?

Yes

**Comment by mocolic** [comment] 2019-01-22 10:40
Thanks for working on the proposal. If I understood correctly, if parent cgroup (ex. fabric) is created and passed to kata runtime, the hierarchy will be:
/sys/fs/cgroup/cpu,cpuacct
└── **_fabric_**
      ├── crio-89e60b84  # Sandbox cgroupsPath=/kubepods/burstable/pod644e04f3/crio-89e60b84
      ├── crio-2a95e0f8  # Container A cgroupsPath=/kubepods/burstable/pod644e04f3/crio-2a95e0f8
      └── crio-d037bce7  # Container B cgroupsPath=/kubepods/burstable/pod644e04f3/crio-d037bce7

Also, how the hierarchy will look like if the parent cgroup is not provided? I would expect something like this:
/sys/fs/cgroup/cpu,cpuacct
      ├── crio-89e60b84  # Sandbox cgroupsPath=/kubepods/burstable/pod644e04f3/crio-89e60b84
      ├── crio-2a95e0f8  # Container A cgroupsPath=/kubepods/burstable/pod644e04f3/crio-2a95e0f8
      └── crio-d037bce7  # Container B cgroupsPath=/kubepods/burstable/pod644e04f3/crio-d037bce7

**Comment by devimc** [comment] 2019-01-22 13:58
@mocolic 
> Also, how the hierarchy will look like if the parent cgroup is not provided? I would expect something like this:
├── crio-89e60b84 # Sandbox cgroupsPath=/kubepods/burstable/pod644e04f3/crio-89e60b84
├── crio-2a95e0f8 # Container A cgroupsPath=/kubepods/burstable/pod644e04f3/crio-2a95e0f8
└── crio-d037bce7 # Container B cgroupsPath=/kubepods/burstable/pod644e04f3/crio-d037bce7

yes

**Comment by mocolic** [comment] 2019-01-22 14:46
Good, this solution will work for Service Fabric. Thanks!

**Comment by jcvenegas** [comment] 2019-01-22 15:35
@mocolic be aware that in the case of Kata the sandbox with more meaningful information is the sandbox cgroup this is going to be the merged cgroup information of all containers created on it. The rest cgroups for the containers may not reflect the information related with the real workload that are running. Just a heads up in case you need to consider that for Fabric.

**Closed** 2019-02-20 16:18 UTC

**Comment by mocolic** [comment] 2019-03-11 18:13
@devimc Thanks for getting this done. Do you know in which version will this be released?

**Comment by devimc** [comment] 2019-03-11 20:33
@mocolic 1.6.0-rc1 https://github.com/kata-containers/runtime/tree/1.6.0-rc1

**Comment by mocolic** [comment] 2019-03-12 15:57
@devimc Thanks! Do you know the timeline for this release?

**Comment by devimc** [comment] 2019-03-12 19:18
@mocolic I don't,  cc @egernst

**Comment by egernst** [comment] 2019-03-12 19:42
scheduled for 2019-03-20

**Comment by mocolic** [comment] 2019-03-20 10:11
@egernst One more question - do you maybe know if this is/could be ported back to 1.5?
